# Praktikum 4: Pengenalan Tensor pada PyTorch

<a href="https://colab.research.google.com/github/pakizhan-ump/ml-umpontianak/blob/main/Modules/Week-02/Praktikum-02/Praktikum_4_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 🎯 Tujuan Praktikum
Mahasiswa memahami struktur data dasar dalam library **PyTorch**, yaitu **Tensor**, dan mampu melakukan operasi-operasi fundamental yang menjadi dasar dari komputasi deep learning.

## 📖 Dasar Teori
**PyTorch** adalah salah satu *framework* deep learning terpopuler. Unit data fundamental di PyTorch adalah **Tensor**. Secara konseptual, sebuah tensor adalah generalisasi dari vektor dan matriks ke dimensi yang lebih tinggi.
* Skalar = Tensor 0D
* Vektor = Tensor 1D
* Matriks = Tensor 2D

Tensor sangat mirip dengan NumPy ndarray, namun memiliki dua keunggulan krusial untuk deep learning:
1.  **Akselerasi GPU:** Tensor dapat dengan mudah dipindahkan ke *Graphics Processing Unit* (GPU) untuk mendapatkan percepatan komputasi yang masif. Ini sangat penting untuk melatih model deep learning yang kompleks pada data besar.
2.  **Dukungan Autograd:** PyTorch dapat secara otomatis melacak histori operasi pada tensor dan menghitung gradien (turunan) dari operasi tersebut. Fitur ini, yang disebut *automatic differentiation*, adalah inti dari algoritma *backpropagation* yang digunakan untuk melatih hampir semua jaringan saraf tiruan.


# 🔧 OPERASI FUNDAMENTAL PYTORCH

In [4]:
#!pip install torch torchvision torchaudio

In [5]:
import torch
import numpy as np

In [6]:
import torch
print(torch.__version__)
print("CUDA available:", torch.cuda.is_available())

2.8.0+cpu
CUDA available: False


# 1. TENSOR CREATION & TYPES

In [7]:
print("=== TENSOR CREATION ===")
# Various creation methods
tensor_zeros = torch.zeros(2, 3)                    # Zeros tensor
tensor_ones = torch.ones(2, 3)                      # Ones tensor  
tensor_rand = torch.rand(2, 3)                      # Random [0,1)
tensor_randn = torch.randn(2, 3)                    # Normal distribution
tensor_arange = torch.arange(0, 10, 2)              # Like range()

print("Zeros tensor:\n", tensor_zeros)
print("Random tensor:\n", tensor_rand)
print("Arange tensor:", tensor_arange)

=== TENSOR CREATION ===
Zeros tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Random tensor:
 tensor([[0.2563, 0.1942, 0.5408],
        [0.6227, 0.8988, 0.5938]])
Arange tensor: tensor([0, 2, 4, 6, 8])


# 2. DATA TYPES & SHAPE

In [8]:
print("\n=== DATA TYPES & SHAPE ===")
tensor_int = torch.tensor([1, 2, 3], dtype=torch.int32)
tensor_float = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)

print("Integer tensor dtype:", tensor_int.dtype)
print("Float tensor dtype:", tensor_float.dtype)
print("Tensor shape:", tensor_float.shape)
print("Tensor size:", tensor_float.size())
print("Number of elements:", tensor_float.numel())


=== DATA TYPES & SHAPE ===
Integer tensor dtype: torch.int32
Float tensor dtype: torch.float32
Tensor shape: torch.Size([3])
Tensor size: torch.Size([3])
Number of elements: 3


# 3. ACCESS & SLICING

In [9]:
print("\n=== ACCESS & SLICING ===")
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original tensor:\n", tensor_2d)
print("Element [1,2]:", tensor_2d[1, 2])
print("First row:", tensor_2d[0, :])
print("Last column:", tensor_2d[:, -1])
print("Submatrix:\n", tensor_2d[0:2, 1:3])


=== ACCESS & SLICING ===
Original tensor:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Element [1,2]: tensor(6)
First row: tensor([1, 2, 3])
Last column: tensor([3, 6, 9])
Submatrix:
 tensor([[2, 3],
        [5, 6]])


# 4. RESHAPING

In [10]:
print("\n=== RESHAPING ===")
tensor_1d = torch.arange(12)
print("Original shape:", tensor_1d.shape)

reshaped = tensor_1d.reshape(3, 4)                  # Reshape
viewed = tensor_1d.view(3, 4)                       # View (shares memory)
transposed = reshaped.T                             # Transpose
flattened = reshaped.flatten()                      # Flatten

print("Reshaped 3x4:\n", reshaped)
print("Transposed 4x3:\n", transposed)
print("Flattened:", flattened)


=== RESHAPING ===
Original shape: torch.Size([12])
Reshaped 3x4:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Transposed 4x3:
 tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
Flattened: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


# 5. MATHEMATICAL OPERATIONS

In [11]:
print("\n=== MATHEMATICAL OPERATIONS ===")
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print("a + b =", a + b)                             # Element-wise
print("a * b =", a * b)
print("a ** 2 =", a ** 2)
print("torch.matmul:", torch.matmul(a, b))          # Dot product
print("torch.sum(a) =", torch.sum(a))               # Reduction


=== MATHEMATICAL OPERATIONS ===
a + b = tensor([5., 7., 9.])
a * b = tensor([ 4., 10., 18.])
a ** 2 = tensor([1., 4., 9.])
torch.matmul: tensor(32.)
torch.sum(a) = tensor(6.)


# 6. AGGREGATION

In [12]:
print("\n=== AGGREGATION ===")
data = torch.randn(4, 5)                            # Random data
print("Data tensor:\n", data)
print("Global sum:", torch.sum(data))
print("Mean along dim 0:", torch.mean(data, dim=0)) # Column means
print("Max along dim 1:", torch.max(data, dim=1))   # Row maximums


=== AGGREGATION ===
Data tensor:
 tensor([[ 2.1043,  0.0182,  0.8012, -0.6319, -0.9294],
        [ 0.3696,  0.1031,  0.6994,  0.8108, -0.6064],
        [-0.7120, -0.2122, -0.5201, -0.3885,  1.4179],
        [-0.2241,  0.6552, -0.6698,  0.3290, -2.0579]])
Global sum: tensor(0.3562)
Mean along dim 0: tensor([ 0.3844,  0.1411,  0.0777,  0.0298, -0.5440])
Max along dim 1: torch.return_types.max(
values=tensor([2.1043, 0.8108, 1.4179, 0.6552]),
indices=tensor([0, 3, 4, 1]))


# 7. BROADCASTING

In [13]:
print("\n=== BROADCASTING ===")
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
vector = torch.tensor([10, 20, 30])

result = matrix + vector                            # Broadcasting
print("Matrix:\n", matrix)
print("Vector:", vector)
print("Broadcast result:\n", result)


=== BROADCASTING ===
Matrix:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Vector: tensor([10, 20, 30])
Broadcast result:
 tensor([[11, 22, 33],
        [14, 25, 36]])


# 8. RANDOM OPERATIONS

In [14]:
print("\n=== RANDOM OPERATIONS ===")
torch.manual_seed(42)                               # Set seed
random_tensor = torch.rand(2, 3)                    # Uniform
normal_tensor = torch.randn(2, 3)                   # Normal
randint_tensor = torch.randint(0, 10, (2, 3))       # Integers

print("Uniform random:\n", random_tensor)
print("Normal random:\n", normal_tensor)
print("Random integers:\n", randint_tensor)


=== RANDOM OPERATIONS ===
Uniform random:
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
Normal random:
 tensor([[ 1.1561,  0.3965, -2.4661],
        [ 0.3623,  0.3765, -0.1808]])
Random integers:
 tensor([[7, 6, 9],
        [6, 3, 1]])


In [15]:
# 9. CONCATENATION & SPLITTING

In [16]:
print("\n=== CONCATENATION & SPLITTING ===")
t1 = torch.tensor([[1, 2], [3, 4]])
t2 = torch.tensor([[5, 6], [7, 8]])

# Concatenation
cat_vertical = torch.cat([t1, t2], dim=0)           # Vertical
cat_horizontal = torch.cat([t1, t2], dim=1)         # Horizontal

print("Vertical concat:\n", cat_vertical)
print("Horizontal concat:\n", cat_horizontal)

# Splitting
chunks = torch.chunk(cat_vertical, 2, dim=0)        # Split into chunks
print("After splitting:")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i}:\n{chunk}")


=== CONCATENATION & SPLITTING ===
Vertical concat:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Horizontal concat:
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
After splitting:
Chunk 0:
tensor([[1, 2],
        [3, 4]])
Chunk 1:
tensor([[5, 6],
        [7, 8]])


In [17]:
# 10. GPU OPERATIONS

In [18]:
print("\n=== GPU OPERATIONS ===")
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor_gpu = tensor_2d.to(device)               # Move to GPU
    print(f"Tensor on: {tensor_gpu.device}")
    
    # Operations on GPU
    result_gpu = tensor_gpu + 1
    print("GPU operation result on CPU:", result_gpu.cpu())
else:
    print("GPU not available, using CPU")


=== GPU OPERATIONS ===
GPU not available, using CPU


In [19]:
# 🏋️ LATIHAN 4: OPERASI PYTORCH UNTUK DEEP LEARNING

### TENSOR OPERATIONS FOR NEURAL NETWORKS ###

In [20]:

'''TODO: Implementasi Operasi Dasar Neural Networks'''
# Simulasi batch data: 32 samples, 10 features
batch_size, n_features = 32, 10
X = torch.randn(batch_size, n_features)
weights = torch.randn(n_features, 1)
bias = torch.randn(1)

# TODO 1: Implementasi linear layer manual: y = XW + b
def linear_layer(X, W, b):
    # TODO: Implementasi operasi linear
    pass

output = linear_layer(X, weights, bias)

# TODO 2: Implementasi ReLU activation function
def relu_activation(tensor):
    # TODO: Implementasi ReLU: max(0, x)
    pass

activated = relu_activation(output)

# TODO 3: Batch normalization sederhana
def simple_batch_norm(tensor):
    # TODO: Normalisasi per feature across batch
    # Formula: (x - mean) / (std + epsilon)
    pass

normalized = simple_batch_norm(X)

# TODO 4: One-hot encoding manual
def one_hot_pytorch(labels, num_classes):
    # TODO: Convert labels to one-hot encoding
    pass

labels = torch.randint(0, 3, (10,))
one_hot = one_hot_pytorch(labels, num_classes=3)

assert output.shape == (batch_size, 1), "Linear output shape incorrect"
assert torch.all(activated >= 0), "ReLU should be >= 0"
assert normalized.shape == X.shape, "Batch norm should preserve shape"
assert one_hot.shape == (10, 3), "One-hot shape incorrect"
print("✅ PyTorch operations completed")

### BONUS: ADVANCED TENSOR OPERATIONS ###

'''TODO: Matrix Multiplication dari Prinsip Dasar'''
def manual_matrix_multiply(A, B):
    """
    Implementasi perkalian matriks manual tanpa torch.matmul
    """
    # TODO: Implementasi perkalian matriks dari dasar
    # Hint: Gunakan nested loops atau broadcasting
    pass

# Test dengan matriks kecil
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

manual_result = manual_matrix_multiply(A, B)
torch_result = torch.matmul(A, B)

assert torch.allclose(manual_result, torch_result), "Manual multiplication incorrect"
print("✅ Advanced tensor operations completed")

AttributeError: 'NoneType' object has no attribute 'shape'